apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmccnobackend
  annotations:
    poc.idm.nttdata.com/gitops-probe: "argo-managed"
spec:
  template:
    spec:
      containers:
        - name: idmccnobackend
          imagePullPolicy: Never
